-- =============================================
-- Миграция 38: снят DML, которым клиент не пользуется
-- =============================================
--
-- ЧТО ЭТО. Доделка миграции 37. Та сняла класс, которым из браузера
-- воспользоваться нечем в принципе (TRUNCATE, REFERENCES, TRIGGER), плюс
-- доказанно лишнее на users и bookings. Остальное было ЗАМОРОЖЕНО в
-- scripts/migration-grants-allowlist.json с пометкой «НЕ СВЕРЕНО»:
-- у reviews и booking_messages есть политики на запись, и снимать
-- табличное право, не прочитав политику, значит менять поведение вслепую.
--
-- Теперь сверено — по политикам И по коду, таблица за таблицей.
--
-- ┌──────────────────┬─────────────────────────┬──────────────────┬─────────┐
-- │ таблица          │ политики RLS            │ код клиента      │ снято   │
-- ├──────────────────┼─────────────────────────┼──────────────────┼─────────┤
-- │ reviews          │ select (public)         │ .select()        │ UPDATE  │
-- │                  │ insert ×2               │ .insert()        │ DELETE  │
-- │ booking_messages │ read, send              │ .select()        │ UPDATE  │
-- │                  │                         │ .insert()        │ DELETE  │
-- │ booking_photos   │ read, add, REMOVE OWN   │ .select()        │ UPDATE  │
-- │                  │                         │ .insert()        │         │
-- │ payments         │ select (свои)           │ НЕ ТРОГАЕТ       │ INSERT  │
-- │                  │                         │                  │ UPDATE  │
-- │                  │                         │                  │ DELETE  │
-- └──────────────────┴─────────────────────────┴──────────────────┴─────────┘
--
-- ПОЧЕМУ У booking_photos СНЯТ ТОЛЬКО UPDATE. Политика
-- «Uploader removes own booking photo» (миграция 11) существует, и DELETE
-- выдан ей осознанно. Кнопки в интерфейсе пока нет, но отсутствие кнопки —
-- не довод разворачивать принятое решение: снимать право надо вместе с
-- политикой и отдельным разбором, а не заодно. Политики на UPDATE нет ни
-- одной, и править чужой снимок продукт не предлагает нигде.
--
-- ПОЧЕМУ У payments ОСТАЁТСЯ SELECT. Политика «Users see own payments»
-- существует с первой миграции, и административный экран на неё
-- рассчитывает. Платежей в продукте сейчас нет вовсе — таблица ждёт, и
-- ждать она должна ТОЛЬКО на чтение.
--
-- ОТКУДА УВЕРЕННОСТЬ ПО КОДУ. Поиск `from('<таблица>')` по src/ и
-- supabase/functions/ (20.09.2026):
--
--   reviews          useCreateUserReview (insert), useUserReviews (select),
--                    ItemDetail (select ×2, insert). UPDATE/DELETE нет.
--                    Отзыв нельзя и переписать: ItemDetail проверяет
--                    maybeSingle(), чтобы не дать второй.
--   booking_messages useSendMessage (insert), useBookingMessages (select).
--   booking_photos   useUploadBookingPhoto (insert), useBookingPhotos
--                    (select). Удаляют их edge-функции
--                    cleanup-orphan-photos и delete-account — обе под
--                    service_role, и revoke их не касается.
--   payments         не встречается ни разу.
--
-- ОТКАТ. Обратное действие — GRANT с теми же именами. Ошибка не молчит:
-- клиент получит 401 / 42501 `permission denied for table …`.
--
-- ПРОВЕРКА НА ЖИВОЙ БАЗЕ ПОСЛЕ ВЫКАТА (ключ anon, ни одной строки не
-- меняется — id заведомо несуществующий):
--
--   DELETE /rest/v1/reviews?id=eq.00000000-0000-0000-0000-000000000000
--   было 204 · ожидается 401
--
--   GET /rest/v1/reviews?select=id&limit=1
--   ожидается 200 — чтение отзывов публично и снятию не подлежит
--
-- =============================================

-- Отзыв пишут один раз. Переписать или снять его продукт не предлагает,
-- и политик на это нет ни одной.
REVOKE UPDATE, DELETE ON public.reviews          FROM anon, authenticated;

-- Переписку по брони не правят и не стирают: она доказательство
-- договорённости для обеих сторон.
REVOKE UPDATE, DELETE ON public.booking_messages FROM anon, authenticated;

-- Снимок передачи и возврата не редактируют. DELETE оставлен: у него есть
-- своя политика, снятая вместе с ней — отдельная работа.
REVOKE UPDATE         ON public.booking_photos   FROM anon, authenticated;

-- Платежей в продукте нет. Таблица ждёт, и ждёт только на чтение.
REVOKE INSERT, UPDATE, DELETE ON public.payments FROM anon, authenticated;
